apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pipeline
description: Simple application delivery pipeline
serialPipeline:
 stages:
 - targetId: dev
 - targetId: pre
   profiles:
   - pre
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: dev cluster
gke:
  cluster: projects/tarea-347513/locations/europe-west1-d/clusters/cloud-deploy
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: pre
description: pre cluster
gke:
  cluster: projects/tarea-347513/locations/europe-west1-d/clusters/cloud-deploy